// test_server.js
//
// Lightweight search server for benchmarking only — do NOT use as a
// production backend. Differences from server.js:
//
//   1. Returns the full top-K candidate list (not just the single winner)
//      so test_result.js can measure top-1, top-3, and top-5 accuracy.
//
//   2. Skips all StatCan fetchMeta() calls. Every cube in the embeddings
//      index was pre-filtered by BuildEmbeddings.js to include all 10
//      Canadian provinces, so the province-count validation that server.js
//      does via live API calls is redundant here. This makes the benchmark
//      order-of-magnitude faster (no network I/O per query).
//
//   3. Dual embedding per request — two separate models serve different roles:
//        RETRIEVAL_MODEL  : embeds the query for cosine similarity against
//                           cubesWithEmbeddings.<retrieval-slug>.json. An
//                           asymmetric retrieval model trained on (short query,
//                           longer passage) pairs, so it handles the mismatch
//                           between 10-word queries and ~87-word enriched cube
//                           text without the mean-pooling distortion that hurt
//                           all-MiniLM-L12-v2. Set ASYMMETRIC=false to fall
//                           back to all-MiniLM-L12-v2 for both roles.
//        CLASSIFIER_EMBEDDING_MODEL (all-MiniLM-L12-v2): embeds the query for
//                           the MLP category classifier inside rerankByCategory.
//                           The MLP was trained on these vectors — this model
//                           never changes regardless of retrieval model choice.
//
//   4. No CORS — intended for local use only (test_result.js → localhost).
//
// Usage:
//   node backend/test_server.js [--port 5001] [--symmetric] [--title-dates]
//   node backend/test_result.js --base-url http://localhost:5001 --delay 0
//
//   --symmetric    use all-MiniLM-L12-v2 for retrieval (single model, no new
//                  embeddings needed). A/B baseline against the current setup.
//   --title-dates  use the asymmetric model but with title+dates embeddings
//                  (cubesWithEmbeddings.multi-qa-MiniLM-L6-cos-v1.title-dates.json)
//                  rather than the enriched text variant. Tests whether the
//                  longer enriched document text actually helps retrieval.
//
// Four benchmark configurations:
//   (1) default              → asymmetric model + enriched text (new approach)
//   (2) --title-dates        → asymmetric model + title+dates  (isolates model gain)
//   (3) --symmetric          → all-MiniLM-L12-v2 + enriched text (current broken)
//   (4) --symmetric --title-dates → all-MiniLM-L12-v2 + title+dates (original 32.3%)

import 'dotenv/config';
import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { pipeline } from '@xenova/transformers';
import {
  getMlpModel,
  rerankByCategory,
  CLASSIFIER_EMBEDDING_MODEL
} from './Search_Utils.js';

// Asymmetric retrieval model. Trained on (query, passage) pairs — handles
// the length mismatch between short queries and enriched cube documents.
// Same 384-dim output as all-MiniLM-L12-v2, so the infrastructure is identical.
// Cube embeddings for this model live in cubesWithEmbeddings.multi-qa-MiniLM-L6-cos-v1.json,
// generated by BuildAsymmetricEmbeddings.js.
const RETRIEVAL_MODEL = "Xenova/multi-qa-MiniLM-L6-cos-v1";

const ASYMMETRIC  = !process.argv.includes('--symmetric');
const TITLE_DATES = process.argv.includes('--title-dates');
const mpdFlagIdx  = process.argv.indexOf('--members-per-dim');
const MEMBERS_PER_DIM = mpdFlagIdx !== -1 ? Number(process.argv[mpdFlagIdx + 1]) : 8;

// Embeddings file selection:
//
//   (1) default              → asymmetric model + enriched text
//       cubesWithEmbeddings.multi-qa-MiniLM-L6-cos-v1.json
//       Generate: node BuildAsymmetricEmbeddings.js
//
//   (2) --title-dates        → asymmetric model + title+dates text
//       cubesWithEmbeddings.multi-qa-MiniLM-L6-cos-v1.title-dates.json
//       Generate: node BuildAsymmetricEmbeddings.js --title-dates
//
//   (3) --symmetric          → all-MiniLM-L12-v2 + enriched text (current 22.4%)
//       cubesWithEmbeddings.all-MiniLM-L12-v2.json  (already exists, modified)
//
//   (4) --symmetric --title-dates → all-MiniLM-L12-v2 + title+dates (original 32.3%)
//       cubesWithEmbeddings.all-MiniLM-L12-v2.json  — BUT this requires reverting
//       the file: git checkout HEAD -- canada-data-pipeline/src/collectors/cubesWithEmbeddings.all-MiniLM-L12-v2.json
//       The symmetric slug is the same filename regardless of --title-dates because
//       the distinction is in which git version of the file is on disk.
const symmetricSlug  = CLASSIFIER_EMBEDDING_MODEL.split('/').pop();
const asymmetricSlug = RETRIEVAL_MODEL.split('/').pop();

function asymmetricFilename(slug) {
  if (TITLE_DATES) return `cubesWithEmbeddings.${slug}.title-dates.json`;
  if (MEMBERS_PER_DIM !== 8) return `cubesWithEmbeddings.${slug}.mpd${MEMBERS_PER_DIM}.json`;
  return `cubesWithEmbeddings.${slug}.json`;
}

const EMBEDDINGS_FILENAME = ASYMMETRIC
  ? asymmetricFilename(asymmetricSlug)
  : `cubesWithEmbeddings.${symmetricSlug}.json`;

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const app = express();
app.use(express.json());

let cachedCubes       = null;
let retrievalModel    = null; // for cosine similarity
let classifierModel   = null; // for MLP input — only used in asymmetric mode

async function loadCubes() {
  if (cachedCubes) return cachedCubes;

  const rootPath     = path.join(process.cwd(), 'canada-data-pipeline', 'src', 'collectors', EMBEDDINGS_FILENAME);
  const internalPath = path.join(__dirname, '../canada-data-pipeline/src/collectors', EMBEDDINGS_FILENAME);

  let resolvedPath;
  try {
    await fs.access(rootPath);
    resolvedPath = rootPath;
  } catch {
    resolvedPath = internalPath;
  }

  console.log(`Database: ${resolvedPath}`);
  const raw = await fs.readFile(resolvedPath, 'utf8');
  cachedCubes = JSON.parse(raw);
  console.log(`Loaded ${cachedCubes.length} cubes.`);
  return cachedCubes;
}

async function getRetrievalModel() {
  if (!retrievalModel) {
    const modelName = ASYMMETRIC ? RETRIEVAL_MODEL : CLASSIFIER_EMBEDDING_MODEL;
    console.log(`Loading retrieval model (${modelName})…`);
    retrievalModel = await pipeline('feature-extraction', modelName);
    console.log('Retrieval model ready.');
  }
  return retrievalModel;
}

// In asymmetric mode: a separate all-MiniLM-L12-v2 instance just for the MLP.
// In symmetric mode: reuse the same model (it's already all-MiniLM-L12-v2).
async function getClassifierModel() {
  if (!ASYMMETRIC) return getRetrievalModel();
  if (!classifierModel) {
    console.log(`Loading classifier model (${CLASSIFIER_EMBEDDING_MODEL})…`);
    classifierModel = await pipeline('feature-extraction', CLASSIFIER_EMBEDDING_MODEL);
    console.log('Classifier model ready.');
  }
  return classifierModel;
}

function cosineSimilarity(a, b) {
  let dot = 0;
  for (let i = 0; i < a.length; i++) dot += a[i] * b[i];
  return dot;
}

// POST /api/search
//
// Response shape (subset of server.js — only fields test_result.js uses):
//   cubeId       — cubeId of the top-1 result after re-ranking (candidates[0])
//   title        — title of the top-1 result
//   cubeCategory — mapped category of the top-1 result
//   candidates   — ordered array of top-K cubeIds from the re-ranked list,
//                  used by test_result.js for top-3 and top-5 accuracy
app.post('/api/search', async (req, res) => {
  try {
    const { query, topK = 5 } = req.body;
    if (!query?.trim()) return res.status(400).json({ error: 'Query is required' });

    const cubes = await loadCubes();

    // Embed the query with both models concurrently. In symmetric mode both
    // calls return the same model instance, so there's no extra work.
    const [retrievalEmb, classifierEmb] = await Promise.all([
      getRetrievalModel().then(m => m(query, { pooling: 'mean', normalize: true })),
      getClassifierModel().then(m => m(query, { pooling: 'mean', normalize: true })),
    ]);

    const qVecRetrieval   = Array.from(retrievalEmb.data);   // for cosine similarity
    const qVecClassifier  = Array.from(classifierEmb.data);  // for MLP in rerankByCategory

    const allScored = cubes
      .map(c => ({ cubeId: c.cubeId, title: c.title, similarity: cosineSimilarity(qVecRetrieval, c.embedding) }))
      .sort((a, b) => b.similarity - a.similarity);

    // rerankByCategory uses qVecClassifier (all-MiniLM-L12-v2) for the MLP,
    // which was trained on those vectors. Retrieval model vectors are NOT
    // passed here — that would break the MLP since it expects 384-dim
    // all-MiniLM-L12-v2 vectors regardless of retrieval model choice.
    const { reranked } = await rerankByCategory(allScored, query, qVecClassifier);
    const ranked = reranked.slice(0, topK);

    if (ranked.length === 0) {
      return res.status(404).json({ error: 'No results', candidates: [] });
    }

    const top = ranked[0];
    return res.json({
      cubeId:       top.cubeId,
      title:        top.title,
      cubeCategory: top.cubeCategory ?? null,
      candidates:   ranked.map(r => r.cubeId),
    });

  } catch (err) {
    console.error('Search error:', err);
    res.status(500).json({ error: 'Internal server error', message: err.message });
  }
});

app.get('/api/health', (_req, res) =>
  res.json({
    status: 'healthy',
    mode: ASYMMETRIC ? 'asymmetric' : 'symmetric',
    retrievalModel: ASYMMETRIC ? RETRIEVAL_MODEL : CLASSIFIER_EMBEDDING_MODEL,
    classifierModel: CLASSIFIER_EMBEDDING_MODEL,
    cubesLoaded: !!cachedCubes,
  })
);

const portFlagIdx = process.argv.indexOf('--port');
const PORT = portFlagIdx !== -1 ? Number(process.argv[portFlagIdx + 1]) : 5000;

const textLabel = TITLE_DATES ? 'title-dates' : `enriched(mpd=${MEMBERS_PER_DIM})`;
const modeLabel = `${ASYMMETRIC ? 'asymmetric' : 'symmetric'} + ${textLabel}`;
console.log(`Mode: ${modeLabel}`);
console.log(`Embeddings: ${EMBEDDINGS_FILENAME}`);

app.listen(PORT, () => console.log(`\nTest server running on port ${PORT}\n`));
loadCubes().catch(console.error);
// Warm up both models at startup so the first request isn't slow
Promise.all([
  getRetrievalModel(),
  getClassifierModel(),
  getMlpModel(),
]).catch(err => console.error('Warm-up failed:', err.message));
